version: '3.8'

services:

  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    pull_policy: always
    ports:
      - 11434:11434
    volumes:
      - ollama_data:/root/.ollama
    tty: true
    restart: unless-stopped
    networks:
      - ollama-docker

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - open-webui_data:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 8080:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - ollama-docker

networks:
  ollama-docker:
    external: false

volumes:
  ollama_data:
  open-webui_data: