apiVersion: v1
kind: Service
metadata:
  name: open-webui-service
  namespace: llm
spec:
  selector:
    app: open-webui
  type: LoadBalancer
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080-tcp