apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: llm
spec:
  selector:
    app: ollama
  type: LoadBalancer
  ports:
    - name: 11434-tcp
      port: 11434
      protocol: TCP
      targetPort: 11434-tcp